### ISSUE TITLE
Italic missing uni00A0

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/Arimo#23]
It seems the non-breaking space is missing.

https://github.com/google/fonts/pull/2625#issuecomment-675976055

**Comment by pichotta** [comment]
Currently both the roman and italic have the /space double encoded to include /nbspace. 

@moyogo  Do you have insight into missing non-breaking space comment?

<img width="441" alt="00A0  2020-08-20 at 8 24 12 PM" src="https://user-images.githubusercontent.com/6576107/90839128-b6988c80-e324-11ea-97d1-9415defd7bea.png">

<img width="405" alt="00A0   2020-08-20 at 8 28 22 PM" src="https://user-images.githubusercontent.com/6576107/90839133-b9937d00-e324-11ea-8563-d0db25422a16.png">

**Comment by pichotta** [comment]
Check the TTFs and VF and the /nbspace is present.
