### ISSUE TITLE
Whitespace glyphs with ink

### ISSUE THREAD

**Issue by moyogo** [TypeNetwork/Arimo#8]
Fontbakery reports uni2028 uni2029 uni205F uni2060 uniFEFF should not have outlines.

uni2028 is LINE SEPARATOR and uni2029 is PARAGRAPH SEPARATOR should be ignored by the font shaper, but they can be made empty and zero-width.

uni205F is MEDIUM MATHEMATICAL SPACE which should be "four-eighteenths of an em" according to the Unicode chart.

uni2060 is WORD JOINER and uniFEFF is ZERO WIDTH NO-BREAK SPACE, both can be empty and zero-width.

**Comment by djrrb** [comment]
Ran this, thanks @moyogo! committed 1b3677fc6982ef1f4773a2e0c8dfa44d0b8bc9a5

```for f in AllFonts():
    for gname in ['uni2028', 'uni2029', 'uni2060', 'uniFEFF']:
        f[gname].clearContours() 
        f[gname].clearComponents() 
        f[gname].width = 0
    f['uni205F'].clearContours()
    f['uni205F'].clearComponents()
    f['uni205F'].width = int(round(4/18 * f.info.unitsPerEm))```
